#!/usr/bin/env sh

### For OSX: Installs brew, and then uses it to install packages I use and/or like to have.
#   NOTE: This should only be packages that I've explicitly installed - not dependencies.
#
# Probably needs some cleanup.

#${SHELL} -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install \
    ali \
    atlas \
    autoconf \
    automake \
    bash-completion \
    bat \
    c-ares \
    ca-certificates \
    cairo \
    capstone \
    cmake \
    colima \
    coreutils \
    crc32c \
    curl \
    docker \
    docker-buildx \
    docker-completion \
    docker-compose \
    dos2unix \
    dylibbundler \
    fd \
    fzf \
    gawk \
    gdb \
    gdbm \
    gdk-pixbuf \
    git \
    git-delta \
    gitstatus \
    gnu-sed \
    gnu-tar \
    gnupg \
    go \
    gradle-completion \
    gzip \
    hadolint \
    harfbuzz \
    htop \
    hugo \
    hurl \
    include-what-you-use \
    jq \
    kind \
    kotlin \
    krb5 \
    krew \
    ktlint \
    kubebuilder \
    kustomize \
    libass \
    libassuan \
    libev \
    libffi \
    libgsf \
    liblinear \
    libmicrohttpd \
    libpq \
    libpthread-stubs \
    librsvg \
    libtermkey \
    libvterm \
    libyaml \
    lima \
    llvm \
    lua \
    luajit \
    luajit-openresty \
    luv \
    macos-term-size \
    make \
    msgpack \
    myman \
    neovim \
    ninja \
    node \
    numpy \
    oauth2l \
    ollama \
    openblas \
    openjdk@17 \
    openssl@3 \
    p7zip \
    pango \
    parallel \
    pcre \
    pinentry \
    pipx \
    postgresql@14 \
    pre-commit \
    prettier \
    python@3.11 \
    python@3.9 \
    qemu \
    ripgrep \
    sdl2 \
    sdl2_gfx \
    sdl2_image \
    sdl2_mixer \
    sdl2_net \
    sdl2_sound \
    sdl2_ttf \
    shellcheck \
    shfmt \
    koekeishiya/formulae/skhd \
    socat \
    sshpass \
    terraform \
    terraformer \
    tflint \
    the_silver_searcher \
    tidy-html5 \
    tree \
    trivy \
    unbound \
    watch \
    wget \
    wrk \
    xz \
    koekeishiya/formulae/yabai \
    yamllint \
    yq \
    zsh \
    zsh-autosuggestions \
    zsh-syntax-highlighting
