--local profile_start_time = vim.loop.hrtime()

local treesitter = require("nvim-treesitter.configs")

treesitter.setup {
    ensure_installed = {
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "commonlisp",
        "cpp",
        "css",
        "dockerfile",
        "dot",
        "glsl",
        "go",
        "gomod",
        "gowork",
        "graphql",
        "haskell",
        "hcl",
        "help",
        "hjson",
        "html",
        "http",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "julia",
        "kotlin",
        "llvm",
        "lua",
        "make",
        "markdown",
        "ninja",
        "norg",
        "org",
        "pascal",
        "perl",
        "php",
        "proto",
        "python",
        "query",
        "r",
        "regex",
        "ruby",
        "rust",
        "scala",
        "scheme",
        "scss",
        "svelte",
        "swift",
        "todotxt",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
    },
    sync_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "gnn",
            node_incremental = "grn",
            scope_incremental = "grc",
            node_decremental = "grm",
        },
    },
    indent = {
        enable = true,
        disable = { "python", "yaml" },
    },
    matchup = {
        enable = true,
        disable = {},
    },
}

--local profile_end_time = vim.loop.hrtime()
--print("lsp_config.lua:", profile_end_time - profile_start_time)
