#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart \
    action="sudo yabai --load-sa"

sudo yabai --load-sa

yabai -m config \
    mouse_follows_focus on \
    focus_follows_mouse autoraise \
    window_origin_display focused \
    window_placement second_child \
    window_shadow float \
    window_opacity off \
    window_opacity_duration 0.0 \
    active_window_opacity 1.0 \
    split_ratio 0.5 \
    split_type auto \
    auto_balance off \
    mouse_modifier alt \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    layout bsp \
    top_padding 0 \
    bottom_padding 0 \
    left_padding 0 \
    right_padding 0 \
    window_gap 0

yabai -m rule --add app="^System Preferences$" sub-layer=above manage=off
yabai -m rule --add app="^System Settings$" sub-layer=above manage=off
yabai -m rule --add app="^System Information$" sub-layer=above manage=off
yabai -m rule --add app="^Mail$" title!="^Inbox.*messages.*$" manage=off
yabai -m rule --add app="^Calendar$" title!="^Calendar$" manage=off

yabai -m signal --add \
    event=window_created \
    app="^Google Chrome$" \
    action="yabai -m query --windows --window \$YABAI_WINDOW_ID | jq --exit-status 'select(.[\"is-topmost\"])' && yabai -m window \$YABAI_WINDOW_ID --toggle topmost"

yabai -m signal --add \
    event=window_created \
    app="^Webex$" \
    action="yabai -m query --windows --window \$YABAI_WINDOW_ID |
    jq --exit-status 'select(.[\"is-topmost\"])' && yabai -m window \$YABAI_WINDOW_ID --toggle topmost"

yabai -m space 1 --label left
yabai -m space 2 --label right
